services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
      POSTGRES_DB: strapi
    ports:
      - "5432:5432"
    volumes:
      - hayling_pg:/var/lib/postgresql/data

volumes:
  hayling_pg:
